library(ggplot2)
library(factoextra)
library(ggsci)

# Jakkard clustering for enriched pathways
# The example here was generated by enrichKEGG()
# function from cluster profiler

setwd(<wd>)

wfisher_all <- read.csv("wFisher_ALL_KEGG.csv", header = T)
head(wfisher_all)
wfisher_all <- subset(wfisher_all, qvalue < 0.01)
dim(wfisher_all)

# Create a data frame with pathway ids and lists of genes
# The pathway ids here will be formed from the ID itself merged
# with pathways description
path_df <- wfisher_all
path_df <- data.frame(id = path_df$X, description = path_df$Description,
                      gene_list = path_df$geneID)
path_ids <- paste(path_df$id, path_df$description, sep = ":")
gene_lists <- strsplit(as.character(path_df$gene_list), "/")
names(gene_lists) <- path_ids

lst <- gene_lists
siml  <- function(x,y) {
  1-length(intersect(lst[[x]],lst[[y]]))/length(union(lst[[x]],lst[[y]]))
}

z <- expand.grid(x=1:length(lst), y=1:length(lst))

result <- mapply(siml,z$x,z$y)
dim(result) <- c(length(lst),length(lst))
colnames(result) <- names(lst)
rownames(result) <- names(lst)
dists <- as.dist(result)
hc <- hclust(dists, method="ward.D2")

fviz_dend(x = hc, cex = 0.5, lwd = 0.8, k = 5,
          k_colors = c("jco"),
          rect = TRUE,
          rect_border = "jco",
          rect_fill = TRUE,
          horiz = TRUE,
          ggtheme = theme_gray())
ggsave(<results.pdf>, device = "pdf", units = "in",
       width = 12, height = 15)
















